image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: Lania.sln

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Lania-UnitTests\bin\Debug\Lania-UnitTests.dll -noshadow" -filter:"+[Lania*]* -[Lania-UnitTests*]*" -output:".\coverage.xml"
- codecov -f "coverage.xml"